server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    fetch-registry: false
    register-with-eureka: true
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka2
