server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: configserver
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/bingquanCao/testfile.git
          searchPaths: cart
          username:
          password:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"

